/* Aquafish PostgreSQL V10：论坛举报、表态与补充权限。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    reason_text VARCHAR(1000),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    assignee_user_id BIGINT,
    resolution VARCHAR(1000),
    resolved_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_forum_reports_queue
    ON ${tablePrefix}forum_reports (status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_forum_reports_target
    ON ${tablePrefix}forum_reports (target_type, target_id, status);
CREATE INDEX IF NOT EXISTS idx_forum_reports_reporter
    ON ${tablePrefix}forum_reports (reporter_user_id, created_at);
COMMENT ON TABLE ${tablePrefix}forum_reports IS '论坛主题、回复和用户举报处理表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(32) NOT NULL DEFAULT 'LIKE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_forum_post_reactions_post_user_type
        UNIQUE (post_id, user_id, reaction_type)
);
CREATE INDEX IF NOT EXISTS idx_forum_post_reactions_user
    ON ${tablePrefix}forum_post_reactions (user_id, created_at);
COMMENT ON TABLE ${tablePrefix}forum_post_reactions IS '论坛帖子点赞、感谢和有用等表态关系表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('forum.report.create', '提交论坛举报', 'action', 'forum', '允许举报主题、回复或用户。', 1, 1, 80),
    ('forum.report.manage', '处理论坛举报', 'action', 'forum', '允许受理和关闭论坛举报。', 1, 1, 200),
    ('forum.reaction.create', '论坛帖子表态', 'action', 'forum', '允许对帖子点赞、感谢或标记有用。', 1, 1, 90)
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'forum'
WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'forum'
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
