/*
 * Aquafish PostgreSQL V6：强论坛第一版数据底座。
 *
 * 该文件与 MySQL/MariaDB V6 表达完全相同的业务结构，
 * 仅使用 PostgreSQL 的自增、时间和冲突处理语法。
 * 所有表名都使用 ${tablePrefix}，不写死安装前缀。
 *
 * 当前不建立跨模块物理外键：用户和角色由 user/core 模块管理，
 * 逻辑关联由领域服务校验，便于备份恢复、分模块升级和数据迁移。
 */

/* 一、论坛板块：第一版领域服务仅允许两级结构。 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    section_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    icon VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    posting_policy VARCHAR(32) NOT NULL DEFAULT 'MEMBERS',
    moderation_policy VARCHAR(32) NOT NULL DEFAULT 'NONE',
    thread_count BIGINT NOT NULL DEFAULT 0,
    post_count BIGINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_forum_sections_section_key UNIQUE (section_key)
);
CREATE INDEX IF NOT EXISTS idx_forum_sections_parent_sort
    ON ${tablePrefix}forum_sections (parent_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_forum_sections_enabled
    ON ${tablePrefix}forum_sections (enabled);
COMMENT ON TABLE ${tablePrefix}forum_sections IS '论坛板块与两级分类表';
COMMENT ON COLUMN ${tablePrefix}forum_sections.section_key IS '不随展示名修改的板块稳定标识';
COMMENT ON COLUMN ${tablePrefix}forum_sections.parent_id IS '父板块 ID，空表示顶级板块';

/* 二、版主授权：后台角色不能代替具体板块范围。 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_section_moderators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    moderator_type VARCHAR(32) NOT NULL DEFAULT 'MODERATOR',
    permission_scope TEXT,
    inherit_children SMALLINT NOT NULL DEFAULT 0,
    starts_at TIMESTAMP(3),
    expires_at TIMESTAMP(3),
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_forum_section_moderators_section_user UNIQUE (section_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_forum_section_moderators_user
    ON ${tablePrefix}forum_section_moderators (user_id, enabled);
CREATE INDEX IF NOT EXISTS idx_forum_section_moderators_expiry
    ON ${tablePrefix}forum_section_moderators (expires_at);
COMMENT ON TABLE ${tablePrefix}forum_section_moderators IS '论坛板块版主范围授权表';

/*
 * 三、主题聚合。
 * next_floor 是下一楼层号，回复事务锁定主题行后递增，
 * 禁止使用 MAX(floor_number) + 1 分配楼层。
 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
    pinned_level SMALLINT NOT NULL DEFAULT 0,
    featured_level SMALLINT NOT NULL DEFAULT 0,
    reply_count BIGINT NOT NULL DEFAULT 0,
    view_count BIGINT NOT NULL DEFAULT 0,
    next_floor BIGINT NOT NULL DEFAULT 2,
    first_post_id BIGINT,
    last_post_id BIGINT,
    last_reply_user_id BIGINT,
    last_reply_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_forum_threads_section_list
    ON ${tablePrefix}forum_threads
    (section_id, status, moderation_status, pinned_level, last_reply_at, id);
CREATE INDEX IF NOT EXISTS idx_forum_threads_author
    ON ${tablePrefix}forum_threads (author_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_forum_threads_last_reply
    ON ${tablePrefix}forum_threads (last_reply_at, id);
COMMENT ON TABLE ${tablePrefix}forum_threads IS '论坛主题聚合与列表统计表';
COMMENT ON COLUMN ${tablePrefix}forum_threads.next_floor IS '下一个可分配楼层，首帖固定为 1';

/* 四、首帖和回复使用同一楼层模型，删除后楼层号不复用。 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    floor_number BIGINT NOT NULL,
    content_text TEXT NOT NULL,
    quoted_post_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
    edited_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3),
    CONSTRAINT uk_forum_posts_thread_floor UNIQUE (thread_id, floor_number)
);
CREATE INDEX IF NOT EXISTS idx_forum_posts_thread_list
    ON ${tablePrefix}forum_posts (thread_id, status, floor_number);
CREATE INDEX IF NOT EXISTS idx_forum_posts_author
    ON ${tablePrefix}forum_posts (author_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_forum_posts_section_moderation
    ON ${tablePrefix}forum_posts (section_id, moderation_status, created_at);
COMMENT ON TABLE ${tablePrefix}forum_posts IS '论坛首帖和回复楼层统一存储表';
COMMENT ON COLUMN ${tablePrefix}forum_posts.floor_number IS '主题内唯一且永不复用的楼层号';

/* 五、主题关注和用户已读位置。 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_thread_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    notification_mode VARCHAR(32) NOT NULL DEFAULT 'ALL_REPLIES',
    last_read_post_id BIGINT,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_forum_thread_subscriptions_thread_user UNIQUE (thread_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_forum_thread_subscriptions_user
    ON ${tablePrefix}forum_thread_subscriptions (user_id, enabled, updated_at);
COMMENT ON TABLE ${tablePrefix}forum_thread_subscriptions IS '论坛主题关注与已读位置表';

/* 六、审核与管理动作只追加，普通业务不允许覆盖历史。 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_moderation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    operator_user_id BIGINT NOT NULL,
    before_state TEXT,
    after_state TEXT,
    reason VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_forum_moderation_actions_target
    ON ${tablePrefix}forum_moderation_actions (target_type, target_id, created_at);
CREATE INDEX IF NOT EXISTS idx_forum_moderation_actions_section
    ON ${tablePrefix}forum_moderation_actions (section_id, created_at);
CREATE INDEX IF NOT EXISTS idx_forum_moderation_actions_operator
    ON ${tablePrefix}forum_moderation_actions (operator_user_id, created_at);
COMMENT ON TABLE ${tablePrefix}forum_moderation_actions IS '论坛不可覆盖的审核与管理动作历史';

/*
 * 七、通知事务发件箱。
 * 发帖与回复事务只写发件箱，投递失败不回滚论坛内容。
 */
CREATE TABLE IF NOT EXISTS ${tablePrefix}forum_notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    delivery_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMP(3),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_forum_notification_outbox_event_key UNIQUE (event_key)
);
CREATE INDEX IF NOT EXISTS idx_forum_notification_outbox_delivery
    ON ${tablePrefix}forum_notification_outbox (delivery_status, available_at, id);
CREATE INDEX IF NOT EXISTS idx_forum_notification_outbox_aggregate
    ON ${tablePrefix}forum_notification_outbox (aggregate_type, aggregate_id);
COMMENT ON TABLE ${tablePrefix}forum_notification_outbox IS '论坛通知事务发件箱';

/*
 * 八、论坛稳定权限节点。
 * ON CONFLICT 仅补充缺失权限，不覆盖现有名称和说明。
 */
INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('forum.thread.read', '阅读论坛主题', 'action', 'forum', '允许查看有权访问板块的主题和楼层。', 1, 1, 10),
    ('forum.thread.create', '发布论坛主题', 'action', 'forum', '允许在符合板块策略时发布新主题。', 1, 1, 20),
    ('forum.thread.reply', '回复论坛主题', 'action', 'forum', '允许回复开放且可回复的主题。', 1, 1, 30),
    ('forum.thread.edit_own', '编辑自己的主题', 'action', 'forum', '允许在规则范围内编辑自己发布的主题。', 1, 1, 40),
    ('forum.post.edit_own', '编辑自己的回复', 'action', 'forum', '允许在规则范围内编辑自己发布的楼层。', 1, 1, 50),
    ('forum.thread.subscribe', '关注论坛主题', 'action', 'forum', '允许关注主题并接收新回复通知。', 1, 1, 60),
    ('forum.attachment.upload', '上传论坛附件', 'action', 'forum', '允许为主题或回复引用已上传的媒体附件。', 1, 1, 70),
    ('forum.section.manage', '管理论坛板块', 'action', 'forum', '允许创建、修改、排序和启停论坛板块。', 1, 1, 100),
    ('forum.thread.audit', '审核论坛主题', 'action', 'forum', '允许审核、拒绝和恢复授权板块的主题。', 1, 1, 110),
    ('forum.thread.close', '关闭论坛主题', 'action', 'forum', '允许关闭或重新打开授权板块的主题。', 1, 1, 120),
    ('forum.thread.pin', '置顶论坛主题', 'action', 'forum', '允许设置或取消主题置顶级别。', 1, 1, 130),
    ('forum.thread.feature', '设置论坛精华', 'action', 'forum', '允许设置或取消主题精华级别。', 1, 1, 140),
    ('forum.thread.move', '移动论坛主题', 'action', 'forum', '允许在授权范围内移动主题所属板块。', 1, 1, 150),
    ('forum.thread.delete', '删除论坛主题', 'action', 'forum', '允许软删除或恢复授权板块的主题。', 1, 1, 160),
    ('forum.post.audit', '审核论坛回复', 'action', 'forum', '允许审核、拒绝和恢复授权板块的回复。', 1, 1, 170),
    ('forum.post.delete', '删除论坛回复', 'action', 'forum', '允许软删除或恢复授权板块的回复。', 1, 1, 180),
    ('forum.moderator.manage', '管理论坛版主', 'action', 'forum', '允许管理板块版主、授权范围和有效期。', 1, 1, 190)
ON CONFLICT (permission_key) DO NOTHING;
