/* Aquafish PostgreSQL V1: core identity and authentication schema. */

CREATE TABLE IF NOT EXISTS ${tablePrefix}options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_key VARCHAR(191) NOT NULL,
    option_value TEXT,
    option_group VARCHAR(64) NOT NULL DEFAULT 'general',
    autoload SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_options_option_key UNIQUE (option_key)
);
CREATE INDEX IF NOT EXISTS idx_options_group ON ${tablePrefix}options (option_group);
CREATE INDEX IF NOT EXISTS idx_options_autoload ON ${tablePrefix}options (autoload);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_key VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 100,
    is_default SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_groups_group_key UNIQUE (group_key)
);
CREATE INDEX IF NOT EXISTS idx_user_groups_sort_order ON ${tablePrefix}user_groups (sort_order);
CREATE INDEX IF NOT EXISTS idx_user_groups_is_default ON ${tablePrefix}user_groups (is_default);

CREATE TABLE IF NOT EXISTS ${tablePrefix}users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(191),
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100),
    avatar VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    group_id BIGINT,
    last_login_at TIMESTAMP(3),
    last_login_ip VARCHAR(45),
    last_user_agent VARCHAR(500),
    login_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_users_status ON ${tablePrefix}users (status);
CREATE INDEX IF NOT EXISTS idx_users_group_id ON ${tablePrefix}users (group_id);
CREATE INDEX IF NOT EXISTS idx_users_last_login_at ON ${tablePrefix}users (last_login_at);
CREATE INDEX IF NOT EXISTS idx_users_last_login_ip ON ${tablePrefix}users (last_login_ip);

CREATE TABLE IF NOT EXISTS ${tablePrefix}roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    built_in SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_roles_role_key UNIQUE (role_key)
);
CREATE INDEX IF NOT EXISTS idx_roles_built_in ON ${tablePrefix}roles (built_in);

CREATE TABLE IF NOT EXISTS ${tablePrefix}permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key VARCHAR(180) NOT NULL,
    name VARCHAR(160) NOT NULL,
    permission_type VARCHAR(50) NOT NULL DEFAULT 'api',
    module_key VARCHAR(120) NOT NULL DEFAULT '',
    description TEXT,
    built_in SMALLINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_permissions_permission_key UNIQUE (permission_key)
);
CREATE INDEX IF NOT EXISTS idx_permissions_module_key ON ${tablePrefix}permissions (module_key);
CREATE INDEX IF NOT EXISTS idx_permissions_type ON ${tablePrefix}permissions (permission_type);
CREATE INDEX IF NOT EXISTS idx_permissions_enabled ON ${tablePrefix}permissions (enabled);
CREATE INDEX IF NOT EXISTS idx_permissions_sort_order ON ${tablePrefix}permissions (sort_order);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_roles_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON ${tablePrefix}user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON ${tablePrefix}user_roles (role_id);

CREATE TABLE IF NOT EXISTS ${tablePrefix}role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_by BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_permissions_role_permission UNIQUE (role_id, permission_id)
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON ${tablePrefix}role_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON ${tablePrefix}role_permissions (permission_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_granted_by ON ${tablePrefix}role_permissions (granted_by);
CREATE INDEX IF NOT EXISTS idx_role_permissions_status ON ${tablePrefix}role_permissions (status);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_login_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    login_name VARCHAR(191) NOT NULL DEFAULT '',
    login_result VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(500),
    ip_address VARCHAR(45),
    remote_address VARCHAR(45),
    x_forwarded_for VARCHAR(500),
    x_real_ip VARCHAR(45),
    user_agent VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_login_logs_user_id ON ${tablePrefix}user_login_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_user_login_logs_login_name ON ${tablePrefix}user_login_logs (login_name);
CREATE INDEX IF NOT EXISTS idx_user_login_logs_ip ON ${tablePrefix}user_login_logs (ip_address);
CREATE INDEX IF NOT EXISTS idx_user_login_logs_result ON ${tablePrefix}user_login_logs (login_result);
CREATE INDEX IF NOT EXISTS idx_user_login_logs_created_at ON ${tablePrefix}user_login_logs (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}admin_operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT NOT NULL DEFAULT 0,
    action_key VARCHAR(180) NOT NULL,
    target_type VARCHAR(80) NOT NULL DEFAULT '',
    target_id BIGINT NOT NULL DEFAULT 0,
    summary VARCHAR(255) NOT NULL DEFAULT '',
    detail TEXT,
    ip VARCHAR(120) NOT NULL DEFAULT '',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_operator_id ON ${tablePrefix}admin_operation_logs (operator_id);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_action_key ON ${tablePrefix}admin_operation_logs (action_key);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_target ON ${tablePrefix}admin_operation_logs (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_admin_operation_logs_created_at ON ${tablePrefix}admin_operation_logs (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}install_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(32) NOT NULL DEFAULT 'INFO',
    message VARCHAR(500) NOT NULL,
    context TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_install_logs_level ON ${tablePrefix}install_logs (level);
CREATE INDEX IF NOT EXISTS idx_install_logs_created_at ON ${tablePrefix}install_logs (created_at);

/* PostgreSQL V1 required installation seed data. */

INSERT INTO ${tablePrefix}user_groups (
    group_key,
    name,
    description,
    sort_order,
    is_default
) VALUES (
    'member',
    '普通用户',
    'Aquafish 系统默认普通用户组',
    100,
    1
)
ON CONFLICT (group_key) DO NOTHING;

INSERT INTO ${tablePrefix}roles (
    role_key,
    name,
    description,
    built_in
) VALUES
    ('super_admin', '超级管理员', '拥有 Aquafish 全部后台权限', 1),
    ('admin', '管理员', 'Aquafish 后台管理员角色', 1),
    ('user', '普通用户', 'Aquafish 前台普通用户角色', 1)
ON CONFLICT (role_key) DO NOTHING;
