/* Aquafish PostgreSQL V7：系统模块与通用媒体。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}system_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    version VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    built_in SMALLINT NOT NULL DEFAULT 0,
    required_flag SMALLINT NOT NULL DEFAULT 0,
    config_json TEXT,
    installed_at TIMESTAMP(3),
    enabled_at TIMESTAMP(3),
    disabled_at TIMESTAMP(3),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_system_modules_status
    ON ${tablePrefix}system_modules (status, module_key);
COMMENT ON TABLE ${tablePrefix}system_modules IS 'Aquafish 模块安装状态与版本登记表';
COMMENT ON COLUMN ${tablePrefix}system_modules.module_key IS '稳定模块标识';
COMMENT ON COLUMN ${tablePrefix}system_modules.status IS 'INSTALLED、ENABLED、DISABLED 或 FAILED';
COMMENT ON COLUMN ${tablePrefix}system_modules.required_flag IS '是否为不可停用的系统必需模块';
COMMENT ON COLUMN ${tablePrefix}system_modules.config_json IS '模块非敏感配置 JSON';

CREATE TABLE IF NOT EXISTS ${tablePrefix}media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    owner_user_id BIGINT,
    storage_provider VARCHAR(64) NOT NULL DEFAULT 'local',
    bucket_name VARCHAR(191) NOT NULL DEFAULT '',
    object_key VARCHAR(500) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    media_type VARCHAR(120) NOT NULL,
    file_extension VARCHAR(32) NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    width INTEGER,
    height INTEGER,
    checksum_sha256 VARCHAR(64) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    status VARCHAR(32) NOT NULL DEFAULT 'READY',
    metadata_json TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3),
    CONSTRAINT uk_media_assets_storage_object
        UNIQUE (storage_provider, bucket_name, object_key)
);
CREATE INDEX IF NOT EXISTS idx_media_assets_owner_created
    ON ${tablePrefix}media_assets (owner_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_media_assets_status_created
    ON ${tablePrefix}media_assets (status, created_at);
CREATE INDEX IF NOT EXISTS idx_media_assets_checksum
    ON ${tablePrefix}media_assets (checksum_sha256);
COMMENT ON TABLE ${tablePrefix}media_assets IS '上传文件与对象存储资源元数据表';
COMMENT ON COLUMN ${tablePrefix}media_assets.public_id IS '对外使用的不可猜测 UUID';
COMMENT ON COLUMN ${tablePrefix}media_assets.object_key IS '存储系统中的对象键';
COMMENT ON COLUMN ${tablePrefix}media_assets.checksum_sha256 IS '文件 SHA-256 摘要';
COMMENT ON COLUMN ${tablePrefix}media_assets.metadata_json IS '尺寸、编码等扩展元数据 JSON';

CREATE TABLE IF NOT EXISTS ${tablePrefix}media_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    usage_type VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_media_usages_asset_target
        UNIQUE (asset_id, target_type, target_id, usage_type)
);
CREATE INDEX IF NOT EXISTS idx_media_usages_target
    ON ${tablePrefix}media_usages (target_type, target_id, usage_type, sort_order);
COMMENT ON TABLE ${tablePrefix}media_usages IS '媒体资源与用户、内容、帖子之间的用途关系表';
COMMENT ON COLUMN ${tablePrefix}media_usages.target_type IS 'USER、ARTICLE、PAGE、FORUM_POST 等';
COMMENT ON COLUMN ${tablePrefix}media_usages.usage_type IS 'AVATAR、COVER、ATTACHMENT、INLINE 等';

INSERT INTO ${tablePrefix}system_modules
    (module_key, name, status, built_in, required_flag, installed_at, enabled_at)
VALUES
    ('core', '系统内核', 'ENABLED', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('setup', '安装与升级', 'ENABLED', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('admin', '后台管理', 'ENABLED', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('user', '用户中心', 'ENABLED', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('forum', '论坛', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('content', '内容与博客', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('theme', '主题', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('plugin', '插件', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('license', '系统授权', 'ENABLED', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('market', '应用市场', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('search', '站内搜索', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ai', 'AI 能力', 'ENABLED', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (module_key) DO UPDATE SET
    name = EXCLUDED.name,
    built_in = EXCLUDED.built_in,
    required_flag = EXCLUDED.required_flag;

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('admin.dashboard.view', '查看后台控制台', 'menu', 'admin', '允许进入后台控制台。', 1, 1, 10),
    ('system.module.view', '查看系统模块', 'action', 'core', '允许查看模块安装状态。', 1, 1, 20),
    ('system.module.manage', '管理系统模块', 'action', 'core', '允许启用、停用和升级可选模块。', 1, 1, 30),
    ('system.settings.view', '查看系统设置', 'menu', 'core', '允许查看站点、固定链接、邮件、存储和安全设置。', 1, 1, 40),
    ('system.settings.update', '修改系统设置', 'action', 'core', '允许修改系统设置。', 1, 1, 50),
    ('system.logs.view', '查看系统日志', 'action', 'core', '允许查看安装日志、登录日志和操作审计。', 1, 1, 60),
    ('media.asset.view', '查看媒体资源', 'action', 'core', '允许查看有权访问的媒体资源。', 1, 1, 70),
    ('media.asset.upload', '上传媒体资源', 'action', 'core', '允许上传媒体文件。', 1, 1, 80),
    ('media.asset.manage', '管理媒体资源', 'action', 'core', '允许审核、删除和恢复媒体资源。', 1, 1, 90)
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key IN ('admin', 'core')
WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key IN ('admin', 'core')
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
