/* Aquafish PostgreSQL V11：实例授权审计。完整签名载荷仍只保存到 workdir。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}license_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id VARCHAR(64) NOT NULL,
    license_id VARCHAR(120) NOT NULL,
    license_type VARCHAR(32) NOT NULL,
    subject_name VARCHAR(191),
    payload_hash VARCHAR(64) NOT NULL,
    signature_key_id VARCHAR(120) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    issued_at TIMESTAMP(3),
    not_before TIMESTAMP(3),
    expires_at TIMESTAMP(3),
    activated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_validated_at TIMESTAMP(3),
    revoked_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_license_activations_instance_license UNIQUE (instance_id, license_id)
);
CREATE INDEX IF NOT EXISTS idx_license_activations_status_expiry
    ON ${tablePrefix}license_activations (status, expires_at);
COMMENT ON TABLE ${tablePrefix}license_activations IS '当前实例的授权激活摘要与有效期审计表';
COMMENT ON COLUMN ${tablePrefix}license_activations.payload_hash IS '完整签名授权载荷 SHA-256 摘要';

CREATE TABLE IF NOT EXISTS ${tablePrefix}license_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activation_id BIGINT NOT NULL,
    feature_key VARCHAR(120) NOT NULL,
    entitlement_type VARCHAR(32) NOT NULL DEFAULT 'BOOLEAN',
    entitlement_value VARCHAR(500) NOT NULL DEFAULT 'true',
    starts_at TIMESTAMP(3),
    expires_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_license_entitlements_activation_feature UNIQUE (activation_id, feature_key)
);
CREATE INDEX IF NOT EXISTS idx_license_entitlements_feature
    ON ${tablePrefix}license_entitlements (feature_key, expires_at);
COMMENT ON TABLE ${tablePrefix}license_entitlements IS '从已验签授权中解析出的功能权益表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}license_validation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activation_id BIGINT,
    validation_source VARCHAR(32) NOT NULL,
    result_code VARCHAR(64) NOT NULL,
    success_flag SMALLINT NOT NULL DEFAULT 0,
    payload_hash VARCHAR(64),
    detail_summary VARCHAR(1000),
    checked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_license_validation_events_activation
    ON ${tablePrefix}license_validation_events (activation_id, checked_at);
CREATE INDEX IF NOT EXISTS idx_license_validation_events_result
    ON ${tablePrefix}license_validation_events (success_flag, result_code, checked_at);
COMMENT ON TABLE ${tablePrefix}license_validation_events IS '本地和在线授权校验的不可覆盖审计事件表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('license.view', '查看系统授权', 'menu', 'license', '允许查看脱敏授权状态和设备码。', 1, 1, 10),
    ('license.activate', '激活系统授权', 'action', 'license', '允许导入或在线激活实例授权。', 1, 1, 20),
    ('license.validate', '重新校验授权', 'action', 'license', '允许触发本地或在线授权校验。', 1, 1, 30),
    ('license.audit.view', '查看授权审计', 'action', 'license', '允许查看脱敏的授权校验历史。', 1, 1, 40)
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'license'
WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'license'
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
