package com.aquafish.core.database.migration;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

class FlywayPostgresqlV1MigrationTest {

    private static final String MIGRATION =
        "db/migration/core/postgresql/"
            + "V1__core_identity_auth_reconciliation.sql";

    @Test
    void shouldProvidePostgresqlCoreSchemaWithoutMysqlSyntax()
        throws IOException {
        String sql = readMigration();

        assertTrue(sql.contains("${tablePrefix}users"));
        assertTrue(sql.contains("${tablePrefix}permissions"));
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(sql.contains("CREATE INDEX IF NOT EXISTS"));
        assertFalse(sql.contains("AUTO_INCREMENT"));
        assertFalse(sql.contains("ENGINE = InnoDB"));
        assertFalse(sql.contains("`"));
    }

    @Test
    void shouldSeedRequiredDefaultGroupAndRolesIdempotently()
        throws IOException {
        String sql = readMigration();

        assertTrue(
            sql.contains("INSERT INTO ${tablePrefix}user_groups")
        );
        assertTrue(
            sql.contains("ON CONFLICT (group_key) DO NOTHING")
        );
        assertTrue(sql.contains("'member'"));

        assertTrue(
            sql.contains("INSERT INTO ${tablePrefix}roles")
        );
        assertTrue(
            sql.contains("ON CONFLICT (role_key) DO NOTHING")
        );
        assertTrue(sql.contains("'super_admin'"));
        assertTrue(sql.contains("'admin'"));
        assertTrue(sql.contains("'user'"));
    }

    private String readMigration() throws IOException {
        try (
            InputStream stream = getClass()
                .getClassLoader()
                .getResourceAsStream(MIGRATION)
        ) {
            assertNotNull(
                stream,
                "PostgreSQL V1 迁移脚本必须打包进 core 模块"
            );
            return new String(
                stream.readAllBytes(),
                StandardCharsets.UTF_8
            );
        }
    }
}
