/* Aquafish PostgreSQL V14：市场软件包缓存与安装历史。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}market_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(120) NOT NULL,
    package_key VARCHAR(191) NOT NULL,
    package_type VARCHAR(32) NOT NULL,
    name VARCHAR(191) NOT NULL,
    latest_version VARCHAR(64) NOT NULL,
    publisher_name VARCHAR(191) NOT NULL DEFAULT '',
    summary VARCHAR(1000),
    manifest_json TEXT NOT NULL,
    signature_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    package_url VARCHAR(1000),
    package_hash VARCHAR(64),
    published_at TIMESTAMP(3),
    synced_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_market_packages_source_package UNIQUE (source_key, package_key)
);
CREATE INDEX IF NOT EXISTS idx_market_packages_type_published
    ON ${tablePrefix}market_packages (package_type, published_at);
COMMENT ON TABLE ${tablePrefix}market_packages IS '受信应用市场的软件包元数据本地缓存表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}market_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_package_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_key VARCHAR(191) NOT NULL,
    from_version VARCHAR(64),
    to_version VARCHAR(64) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    operator_user_id BIGINT NOT NULL,
    package_hash VARCHAR(64) NOT NULL,
    error_summary VARCHAR(1000),
    started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_market_installations_target
    ON ${tablePrefix}market_installations (target_type, target_key, started_at);
CREATE INDEX IF NOT EXISTS idx_market_installations_status
    ON ${tablePrefix}market_installations (status, started_at);
COMMENT ON TABLE ${tablePrefix}market_installations IS '市场主题和插件安装、升级及回滚审计表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('market.view', '查看应用市场', 'menu', 'market', '允许浏览受信市场包。', 1, 1, 10),
    ('market.sync', '同步应用市场', 'action', 'market', '允许同步市场清单。', 1, 1, 20),
    ('market.install', '安装市场软件包', 'action', 'market', '允许安装或升级已验签主题和插件。', 1, 1, 30),
    ('market.history.view', '查看市场安装历史', 'action', 'market', '允许查看安装、升级和回滚记录。', 1, 1, 40)
ON CONFLICT (permission_key) DO NOTHING;
INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE' FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'market' WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;
INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'market' WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
