package com.aquafish.forum.database;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.aquafish.forum.permission.ForumPermissions;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * 论坛 V6 基础结构与 V17 默认会员权限迁移静态契约测试。
 *
 * <p>本测试不冒充真实数据库矩阵，它负责在快速单元测试阶段阻止：</p>
 *
 * <ol>
 *     <li>漏建论坛核心表；</li>
 *     <li>MySQL 和 PostgreSQL 两个方言的权限节点不一致；</li>
 *     <li>写死 aq_ 表前缀；</li>
 *     <li>楼层分配误用 MAX(floor_number) + 1。</li>
 * </ol>
 */
class ForumFoundationMigrationTest {

    private static final String MYSQL =
        "db/migration/forum/mysql/V6__forum_foundation.sql";
    private static final String POSTGRESQL =
        "db/migration/forum/postgresql/V6__forum_foundation.sql";
    private static final String MYSQL_MEMBER_PERMISSIONS =
        "db/migration/forum/mysql/V17__forum_member_permissions.sql";
    private static final String POSTGRESQL_MEMBER_PERMISSIONS =
        "db/migration/forum/postgresql/V17__forum_member_permissions.sql";

    private static final List<String> REQUIRED_TABLES = List.of(
        ForumTableNames.SECTIONS,
        ForumTableNames.SECTION_MODERATORS,
        ForumTableNames.THREADS,
        ForumTableNames.POSTS,
        ForumTableNames.THREAD_SUBSCRIPTIONS,
        ForumTableNames.MODERATION_ACTIONS,
        ForumTableNames.NOTIFICATION_OUTBOX
    );

    @Test
    void bothDialectsShouldDeclareEquivalentForumFoundation() throws IOException {
        String mysql = resource(MYSQL);
        String postgresql = resource(POSTGRESQL);

        for (String table : REQUIRED_TABLES) {
            assertTrue(mysql.contains("${tablePrefix}" + table), "MySQL 缺少表：" + table);
            assertTrue(postgresql.contains("${tablePrefix}" + table), "PostgreSQL 缺少表：" + table);
        }

        List<String> permissions = new java.util.ArrayList<>();
        permissions.addAll(ForumPermissions.MEMBER_PERMISSIONS);
        permissions.addAll(ForumPermissions.MANAGEMENT_PERMISSIONS);
        assertEquals(17, permissions.stream().distinct().count());

        for (String permission : permissions) {
            assertTrue(mysql.contains("'" + permission + "'"), "MySQL 缺少权限：" + permission);
            assertTrue(postgresql.contains("'" + permission + "'"), "PostgreSQL 缺少权限：" + permission);
        }
    }

    @Test
    void migrationsShouldKeepDynamicPrefixAndAtomicFloorCounter() throws IOException {
        String mysql = resource(MYSQL);
        String postgresql = resource(POSTGRESQL);

        assertFalse(mysql.contains("aq_forum_"));
        assertFalse(postgresql.contains("aq_forum_"));
        assertTrue(mysql.contains("next_floor"));
        assertTrue(postgresql.contains("next_floor"));
        /*
         * 注释中会明确写出“禁止 MAX(floor_number) + 1”，
         * 因此这里检查可执行查询特征 SELECT MAX，不把说明性注释当成 SQL。
         */
        assertFalse(mysql.toLowerCase().contains("select max(floor_number)"));
        assertFalse(postgresql.toLowerCase().contains("select max(floor_number)"));
    }

    @Test
    void eachDialectShouldUseItsOwnIdentityAndConflictSyntax() throws IOException {
        String mysql = resource(MYSQL).toLowerCase();
        String postgresql = resource(POSTGRESQL).toLowerCase();

        assertTrue(mysql.contains("auto_increment"));
        assertTrue(mysql.contains("insert ignore"));
        assertFalse(mysql.contains("generated by default as identity"));

        assertTrue(postgresql.contains("generated by default as identity"));
        assertTrue(postgresql.contains("on conflict (permission_key) do nothing"));
        assertFalse(postgresql.contains("auto_increment"));
    }

    @Test
    void defaultMemberGroupShouldReceiveOnlyForumMemberPermissions() throws IOException {
        String mysql = resource(MYSQL_MEMBER_PERMISSIONS);
        String postgresql = resource(POSTGRESQL_MEMBER_PERMISSIONS);

        for (String permission : ForumPermissions.MEMBER_PERMISSIONS) {
            assertTrue(mysql.contains("'" + permission + "'"));
            assertTrue(postgresql.contains("'" + permission + "'"));
        }
        for (String permission : ForumPermissions.MANAGEMENT_PERMISSIONS) {
            assertFalse(mysql.contains("'" + permission + "'"));
            assertFalse(postgresql.contains("'" + permission + "'"));
        }

        assertTrue(mysql.contains("${tablePrefix}user_group_permissions"));
        assertTrue(postgresql.contains("${tablePrefix}user_group_permissions"));
        assertFalse(mysql.contains("aq_user_group_permissions"));
        assertFalse(postgresql.contains("aq_user_group_permissions"));
        assertTrue(mysql.toLowerCase().contains("insert ignore"));
        assertTrue(postgresql.toLowerCase().contains(
            "on conflict (group_id, permission_key) do nothing"
        ));
    }

    /** 从当前 forum 模块测试类路径读取真实迁移文件。 */
    private String resource(String path) throws IOException {
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(path)) {
            if (input == null) {
                throw new IllegalStateException("论坛迁移资源不存在：" + path);
            }
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
