/* Aquafish PostgreSQL V12：主题登记与站点级主题设置。主题文件仍保存于 workdir/themes。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_key VARCHAR(120) NOT NULL,
    name VARCHAR(191) NOT NULL,
    version VARCHAR(64) NOT NULL,
    author_name VARCHAR(191) NOT NULL DEFAULT '',
    description TEXT,
    parent_theme_key VARCHAR(120),
    package_hash VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'UPLOAD',
    status VARCHAR(32) NOT NULL DEFAULT 'INSTALLED',
    active_flag SMALLINT NOT NULL DEFAULT 0,
    installed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMP(3),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_themes_theme_key UNIQUE (theme_key)
);
CREATE INDEX IF NOT EXISTS idx_themes_active_status ON ${tablePrefix}themes (active_flag, status);
COMMENT ON TABLE ${tablePrefix}themes IS '已安装主题清单、版本和启用状态表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}theme_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id BIGINT NOT NULL,
    site_scope VARCHAR(120) NOT NULL DEFAULT 'default',
    setting_key VARCHAR(191) NOT NULL,
    setting_value TEXT,
    value_type VARCHAR(32) NOT NULL DEFAULT 'STRING',
    updated_by BIGINT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_theme_settings_scope_key UNIQUE (theme_id, site_scope, setting_key)
);
CREATE INDEX IF NOT EXISTS idx_theme_settings_scope ON ${tablePrefix}theme_settings (site_scope, theme_id);
COMMENT ON TABLE ${tablePrefix}theme_settings IS '主题按站点范围保存的结构化设置表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('theme.view', '查看主题', 'menu', 'theme', '允许查看已安装主题。', 1, 1, 10),
    ('theme.install', '安装主题', 'action', 'theme', '允许校验并安装主题包。', 1, 1, 20),
    ('theme.activate', '启用主题', 'action', 'theme', '允许启用、切换和回滚主题。', 1, 1, 30),
    ('theme.settings.manage', '管理主题设置', 'action', 'theme', '允许修改当前主题的站点设置。', 1, 1, 40),
    ('theme.uninstall', '卸载主题', 'action', 'theme', '允许卸载未启用且未被依赖的主题。', 1, 1, 50)
ON CONFLICT (permission_key) DO NOTHING;
INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE' FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'theme' WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;
INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'theme' WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
