/* Aquafish PostgreSQL V2: user profiles, statistics and points. */

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    real_name VARCHAR(120) NOT NULL DEFAULT '',
    nickname VARCHAR(120) NOT NULL DEFAULT '',
    gender VARCHAR(32) NOT NULL DEFAULT 'unknown',
    birthday VARCHAR(32) NOT NULL DEFAULT '',
    location VARCHAR(255) NOT NULL DEFAULT '',
    bio TEXT,
    signature TEXT,
    website VARCHAR(255) NOT NULL DEFAULT '',
    qq VARCHAR(80) NOT NULL DEFAULT '',
    wechat VARCHAR(120) NOT NULL DEFAULT '',
    profile_completed INTEGER NOT NULL DEFAULT 0,
    audit_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_profiles_nickname ON ${tablePrefix}user_profiles (nickname);
CREATE INDEX IF NOT EXISTS idx_user_profiles_audit_status ON ${tablePrefix}user_profiles (audit_status);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_profile_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    field_type VARCHAR(50) NOT NULL DEFAULT 'text',
    placeholder VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT,
    required_flag SMALLINT NOT NULL DEFAULT 0,
    editable_flag SMALLINT NOT NULL DEFAULT 1,
    public_flag SMALLINT NOT NULL DEFAULT 1,
    audit_required SMALLINT NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_profile_fields_field_key UNIQUE (field_key)
);
CREATE INDEX IF NOT EXISTS idx_user_profile_fields_enabled ON ${tablePrefix}user_profile_fields (enabled);
CREATE INDEX IF NOT EXISTS idx_user_profile_fields_sort_order ON ${tablePrefix}user_profile_fields (sort_order);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_profile_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    field_key VARCHAR(120) NOT NULL DEFAULT '',
    old_value TEXT,
    new_value TEXT,
    audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    audit_message TEXT,
    operator_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_profile_audits_user_id ON ${tablePrefix}user_profile_audits (user_id);
CREATE INDEX IF NOT EXISTS idx_user_profile_audits_field_key ON ${tablePrefix}user_profile_audits (field_key);
CREATE INDEX IF NOT EXISTS idx_user_profile_audits_status ON ${tablePrefix}user_profile_audits (audit_status);
CREATE INDEX IF NOT EXISTS idx_user_profile_audits_operator_id ON ${tablePrefix}user_profile_audits (operator_id);
CREATE INDEX IF NOT EXISTS idx_user_profile_audits_created_at ON ${tablePrefix}user_profile_audits (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    posts_count BIGINT NOT NULL DEFAULT 0,
    threads_count BIGINT NOT NULL DEFAULT 0,
    comments_count BIGINT NOT NULL DEFAULT 0,
    followers_count BIGINT NOT NULL DEFAULT 0,
    following_count BIGINT NOT NULL DEFAULT 0,
    friends_count BIGINT NOT NULL DEFAULT 0,
    points BIGINT NOT NULL DEFAULT 0,
    credits BIGINT NOT NULL DEFAULT 0,
    last_active_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_statistics_user_id UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_statistics_points ON ${tablePrefix}user_statistics (points);
CREATE INDEX IF NOT EXISTS idx_user_statistics_last_active_at ON ${tablePrefix}user_statistics (last_active_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}points_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_key VARCHAR(160) NOT NULL,
    name VARCHAR(160) NOT NULL,
    scene VARCHAR(120) NOT NULL DEFAULT '',
    points_delta BIGINT NOT NULL DEFAULT 0,
    daily_limit BIGINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    description TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_points_rules_rule_key UNIQUE (rule_key)
);
CREATE INDEX IF NOT EXISTS idx_points_rules_scene ON ${tablePrefix}points_rules (scene);
CREATE INDEX IF NOT EXISTS idx_points_rules_enabled ON ${tablePrefix}points_rules (enabled);

CREATE TABLE IF NOT EXISTS ${tablePrefix}points_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rule_key VARCHAR(160) NOT NULL DEFAULT '',
    points_delta BIGINT NOT NULL DEFAULT 0,
    balance_after BIGINT NOT NULL DEFAULT 0,
    source_type VARCHAR(120) NOT NULL DEFAULT '',
    source_id BIGINT NOT NULL DEFAULT 0,
    remark TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_points_logs_user_created ON ${tablePrefix}points_logs (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_points_logs_rule_key ON ${tablePrefix}points_logs (rule_key);
CREATE INDEX IF NOT EXISTS idx_points_logs_source ON ${tablePrefix}points_logs (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_points_logs_created_at ON ${tablePrefix}points_logs (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}points_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL DEFAULT 0,
    points_delta BIGINT NOT NULL DEFAULT 0,
    reason TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_points_adjustments_user_created ON ${tablePrefix}points_adjustments (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_points_adjustments_operator_id ON ${tablePrefix}points_adjustments (operator_id);
CREATE INDEX IF NOT EXISTS idx_points_adjustments_created_at ON ${tablePrefix}points_adjustments (created_at);

INSERT INTO ${tablePrefix}user_statistics (user_id)
SELECT u.id FROM ${tablePrefix}users u
ON CONFLICT (user_id) DO NOTHING;
