/* Aquafish PostgreSQL V3: user tags, group capabilities and bans. */

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(50) NOT NULL DEFAULT '',
    description TEXT,
    built_in SMALLINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_tags_tag_key UNIQUE (tag_key)
);
CREATE INDEX IF NOT EXISTS idx_user_tags_name ON ${tablePrefix}user_tags (name);
CREATE INDEX IF NOT EXISTS idx_user_tags_enabled_sort ON ${tablePrefix}user_tags (enabled, sort_order);
CREATE INDEX IF NOT EXISTS idx_user_tags_built_in ON ${tablePrefix}user_tags (built_in);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_tag_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_tag_relations_user_tag UNIQUE (user_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_user_tag_relations_user_id ON ${tablePrefix}user_tag_relations (user_id);
CREATE INDEX IF NOT EXISTS idx_user_tag_relations_tag_id ON ${tablePrefix}user_tag_relations (tag_id);
CREATE INDEX IF NOT EXISTS idx_user_tag_relations_created_at ON ${tablePrefix}user_tag_relations (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_group_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    permission_key VARCHAR(160) NOT NULL,
    permission_value TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_group_permissions_group_key UNIQUE (group_id, permission_key)
);
CREATE INDEX IF NOT EXISTS idx_user_group_permissions_group_id ON ${tablePrefix}user_group_permissions (group_id);
CREATE INDEX IF NOT EXISTS idx_user_group_permissions_permission_key ON ${tablePrefix}user_group_permissions (permission_key);

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ban_type VARCHAR(50) NOT NULL DEFAULT 'login',
    reason TEXT,
    operator_id BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP(3),
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_bans_user_enabled ON ${tablePrefix}user_bans (user_id, enabled);
CREATE INDEX IF NOT EXISTS idx_user_bans_type_enabled ON ${tablePrefix}user_bans (ban_type, enabled);
CREATE INDEX IF NOT EXISTS idx_user_bans_expired_at ON ${tablePrefix}user_bans (expired_at);
CREATE INDEX IF NOT EXISTS idx_user_bans_operator_id ON ${tablePrefix}user_bans (operator_id);
CREATE INDEX IF NOT EXISTS idx_user_bans_created_at ON ${tablePrefix}user_bans (created_at);

CREATE TABLE IF NOT EXISTS ${tablePrefix}ip_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_value VARCHAR(120) NOT NULL,
    ban_type VARCHAR(50) NOT NULL DEFAULT 'access',
    reason TEXT,
    operator_id BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP(3),
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ip_bans_value_enabled ON ${tablePrefix}ip_bans (ip_value, enabled);
CREATE INDEX IF NOT EXISTS idx_ip_bans_type_enabled ON ${tablePrefix}ip_bans (ban_type, enabled);
CREATE INDEX IF NOT EXISTS idx_ip_bans_expired_at ON ${tablePrefix}ip_bans (expired_at);
CREATE INDEX IF NOT EXISTS idx_ip_bans_operator_id ON ${tablePrefix}ip_bans (operator_id);
CREATE INDEX IF NOT EXISTS idx_ip_bans_created_at ON ${tablePrefix}ip_bans (created_at);
