/* Aquafish PostgreSQL V5：用户公开身份与后台管理组正式结构。 */

ALTER TABLE ${tablePrefix}users
    ADD COLUMN IF NOT EXISTS public_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS register_source VARCHAR(64) NOT NULL DEFAULT 'legacy',
    ADD COLUMN IF NOT EXISTS register_ip VARCHAR(45);

UPDATE ${tablePrefix}users
SET public_id = 'AQUA_' || LPAD(TO_HEX(id), 16, '0')
WHERE public_id IS NULL OR BTRIM(public_id) = '';

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_public_id
    ON ${tablePrefix}users (public_id);

CREATE TABLE IF NOT EXISTS ${tablePrefix}admin_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_key VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    built_in SMALLINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ${tablePrefix}admin_groups IS '后台管理员分组表';
COMMENT ON COLUMN ${tablePrefix}admin_groups.group_key IS '管理组稳定标识';
COMMENT ON COLUMN ${tablePrefix}admin_groups.built_in IS '是否为系统内置管理组';
COMMENT ON COLUMN ${tablePrefix}admin_groups.enabled IS '管理组是否启用';
CREATE INDEX IF NOT EXISTS idx_admin_groups_sort_order
    ON ${tablePrefix}admin_groups (sort_order);

CREATE TABLE IF NOT EXISTS ${tablePrefix}admin_group_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_group_users_group_user UNIQUE (group_id, user_id)
);
COMMENT ON TABLE ${tablePrefix}admin_group_users IS '管理组与管理员用户关联表';
COMMENT ON COLUMN ${tablePrefix}admin_group_users.group_id IS '管理组 ID';
COMMENT ON COLUMN ${tablePrefix}admin_group_users.user_id IS '管理员用户 ID';
CREATE INDEX IF NOT EXISTS idx_admin_group_users_user_id
    ON ${tablePrefix}admin_group_users (user_id);

CREATE TABLE IF NOT EXISTS ${tablePrefix}admin_group_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_group_permissions_group_permission
        UNIQUE (group_id, permission_id)
);
CREATE INDEX IF NOT EXISTS idx_admin_group_permissions_permission_id
    ON ${tablePrefix}admin_group_permissions (permission_id);
COMMENT ON TABLE ${tablePrefix}admin_group_permissions IS '管理组与权限节点关联表';
COMMENT ON COLUMN ${tablePrefix}admin_group_permissions.group_id IS '管理组 ID';
COMMENT ON COLUMN ${tablePrefix}admin_group_permissions.permission_id IS '权限节点 ID';

INSERT INTO ${tablePrefix}admin_groups
    (group_key, name, description, built_in, enabled, sort_order)
VALUES
    ('super_admin', '超级管理员', '拥有后台全部权限。', 1, 1, 1),
    ('admin', '系统管理员', '负责系统基础配置和用户管理。', 1, 1, 10),
    ('content_auditor', '内容审核员', '负责内容、帖子、评论和资料审核。', 1, 1, 20),
    ('operator', '运营人员', '负责推荐、标签、积分和用户运营。', 1, 1, 30),
    ('moderator_admin', '版主管理员', '负责论坛版块和版主体系管理。', 1, 1, 40)
ON CONFLICT (group_key) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_users (group_id, user_id)
SELECT g.id, ur.user_id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}roles r ON r.role_key = 'super_admin'
JOIN ${tablePrefix}user_roles ur ON ur.role_id = r.id
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, user_id) DO NOTHING;
