/* Aquafish PostgreSQL V8：用户安全、关系与认证。 */

ALTER TABLE ${tablePrefix}users
    ALTER COLUMN public_id SET NOT NULL;
COMMENT ON COLUMN ${tablePrefix}users.public_id IS '用户对外公开稳定编号';
COMMENT ON COLUMN ${tablePrefix}users.register_source IS '账号注册来源';
COMMENT ON COLUMN ${tablePrefix}users.register_ip IS '注册来源 IP';

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_type VARCHAR(32) NOT NULL DEFAULT 'WEB',
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(3) NOT NULL,
    revoked_at TIMESTAMP(3),
    revoke_reason VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_active
    ON ${tablePrefix}user_sessions (user_id, revoked_at, expires_at);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at
    ON ${tablePrefix}user_sessions (expires_at);
COMMENT ON TABLE ${tablePrefix}user_sessions IS '前台、后台和 API 登录会话表';
COMMENT ON COLUMN ${tablePrefix}user_sessions.token_hash IS '会话令牌 SHA-256 摘要，禁止保存原始令牌';

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_key VARCHAR(64) NOT NULL,
    provider_user_id VARCHAR(191) NOT NULL,
    display_name VARCHAR(191) NOT NULL DEFAULT '',
    credential_ciphertext TEXT,
    credential_key_version VARCHAR(64) NOT NULL DEFAULT '',
    metadata_json TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_oauth_provider_user UNIQUE (provider_key, provider_user_id),
    CONSTRAINT uk_user_oauth_user_provider UNIQUE (user_id, provider_key)
);
COMMENT ON TABLE ${tablePrefix}user_oauth_accounts IS '用户第三方登录账号绑定表';
COMMENT ON COLUMN ${tablePrefix}user_oauth_accounts.credential_ciphertext IS '应用层加密后的可刷新凭据';

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    relationship_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_relationships_pair
        UNIQUE (source_user_id, target_user_id, relationship_type)
);
CREATE INDEX IF NOT EXISTS idx_user_relationships_target
    ON ${tablePrefix}user_relationships (target_user_id, relationship_type, status);
CREATE INDEX IF NOT EXISTS idx_user_relationships_source
    ON ${tablePrefix}user_relationships (source_user_id, relationship_type, status);
COMMENT ON TABLE ${tablePrefix}user_relationships IS '关注、好友和屏蔽关系统一表';
COMMENT ON COLUMN ${tablePrefix}user_relationships.relationship_type IS 'FOLLOW、FRIEND 或 BLOCK';

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    verification_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    evidence_ciphertext TEXT,
    evidence_key_version VARCHAR(64) NOT NULL DEFAULT '',
    reviewer_user_id BIGINT,
    review_note VARCHAR(500),
    verified_at TIMESTAMP(3),
    expires_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_verifications_user_type
    ON ${tablePrefix}user_verifications (user_id, verification_type, status);
CREATE INDEX IF NOT EXISTS idx_user_verifications_review
    ON ${tablePrefix}user_verifications (status, created_at);
CREATE INDEX IF NOT EXISTS idx_user_verifications_reviewer
    ON ${tablePrefix}user_verifications (reviewer_user_id, updated_at);
COMMENT ON TABLE ${tablePrefix}user_verifications IS '邮箱、手机、实名和组织认证记录表';
COMMENT ON COLUMN ${tablePrefix}user_verifications.evidence_ciphertext IS '应用层加密后的认证材料';

CREATE TABLE IF NOT EXISTS ${tablePrefix}user_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    purpose VARCHAR(64) NOT NULL,
    target_value VARCHAR(191) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP(3) NOT NULL,
    consumed_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_verification_tokens_target
    ON ${tablePrefix}user_verification_tokens (purpose, target_value, expires_at);
CREATE INDEX IF NOT EXISTS idx_user_verification_tokens_user
    ON ${tablePrefix}user_verification_tokens (user_id, purpose, created_at);
COMMENT ON TABLE ${tablePrefix}user_verification_tokens IS '邮箱验证、找回密码等一次性令牌表';
COMMENT ON COLUMN ${tablePrefix}user_verification_tokens.token_hash IS '一次性令牌 SHA-256 摘要';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('user.view', '查看用户', 'menu', 'user', '允许查看用户列表和详情。', 1, 1, 10),
    ('user.manage', '管理用户', 'action', 'user', '允许修改用户状态和基础资料。', 1, 1, 20),
    ('user.profile_field.manage', '管理用户栏目', 'action', 'user', '允许维护用户资料字段。', 1, 1, 30),
    ('user.statistics.view', '查看用户统计', 'action', 'user', '允许查看用户行为和积分统计。', 1, 1, 40),
    ('user.tag.manage', '管理用户标签', 'action', 'user', '允许维护并分配运营标签。', 1, 1, 50),
    ('user.ban.manage', '管理用户封禁', 'action', 'user', '允许封禁用户和 IP。', 1, 1, 60),
    ('user.points.manage', '管理用户积分', 'action', 'user', '允许配置积分规则和人工奖惩。', 1, 1, 70),
    ('user.relationship.manage', '管理用户关系', 'action', 'user', '允许处理关注、好友和屏蔽关系。', 1, 1, 80),
    ('user.verification.manage', '管理用户认证', 'action', 'user', '允许审核用户认证。', 1, 1, 90),
    ('user.group.manage', '管理用户组', 'action', 'user', '允许维护前台用户组及社区权限。', 1, 1, 100),
    ('user.admin.manage', '管理管理员', 'action', 'user', '允许授予或取消后台管理员身份。', 1, 1, 110),
    ('user.admin_group.manage', '管理后台管理组', 'action', 'user', '允许维护管理组与管理组权限。', 1, 1, 120),
    ('user.role.manage', '管理角色', 'action', 'user', '允许维护系统角色。', 1, 1, 130),
    ('user.permission.manage', '管理权限节点', 'action', 'user', '允许维护角色和权限节点关系。', 1, 1, 140),
    ('user.session.revoke', '注销用户会话', 'action', 'user', '允许强制注销用户登录会话。', 1, 1, 150)
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'user'
WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'user'
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
