/* Aquafish PostgreSQL V13：插件登记、配置与授权。插件文件仍保存于 workdir/plugins。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}plugins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_key VARCHAR(120) NOT NULL,
    name VARCHAR(191) NOT NULL,
    version VARCHAR(64) NOT NULL,
    provider_name VARCHAR(191) NOT NULL DEFAULT '',
    description TEXT,
    main_class VARCHAR(500) NOT NULL,
    package_hash VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'UPLOAD',
    status VARCHAR(32) NOT NULL DEFAULT 'INSTALLED',
    enabled_flag SMALLINT NOT NULL DEFAULT 0,
    installed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enabled_at TIMESTAMP(3),
    disabled_at TIMESTAMP(3),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plugins_plugin_key UNIQUE (plugin_key)
);
CREATE INDEX IF NOT EXISTS idx_plugins_enabled_status ON ${tablePrefix}plugins (enabled_flag, status);
COMMENT ON TABLE ${tablePrefix}plugins IS '已安装插件清单、版本和生命周期状态表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}plugin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_id BIGINT NOT NULL,
    setting_key VARCHAR(191) NOT NULL,
    setting_value TEXT,
    value_type VARCHAR(32) NOT NULL DEFAULT 'STRING',
    secret_flag SMALLINT NOT NULL DEFAULT 0,
    encryption_key_version VARCHAR(64) NOT NULL DEFAULT '',
    updated_by BIGINT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plugin_settings_plugin_key UNIQUE (plugin_id, setting_key)
);
COMMENT ON TABLE ${tablePrefix}plugin_settings IS '插件结构化配置与加密敏感配置表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}plugin_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_id BIGINT NOT NULL,
    capability_key VARCHAR(191) NOT NULL,
    risk_level VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    granted_flag SMALLINT NOT NULL DEFAULT 0,
    granted_by BIGINT,
    granted_at TIMESTAMP(3),
    revoked_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plugin_permissions_plugin_capability UNIQUE (plugin_id, capability_key)
);
CREATE INDEX IF NOT EXISTS idx_plugin_permissions_granted
    ON ${tablePrefix}plugin_permissions (granted_flag, risk_level);
COMMENT ON TABLE ${tablePrefix}plugin_permissions IS '插件访问文件、网络和数据等系统能力授权表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('plugin.view', '查看插件', 'menu', 'plugin', '允许查看已安装插件。', 1, 1, 10),
    ('plugin.install', '安装插件', 'action', 'plugin', '允许校验并安装插件包。', 1, 1, 20),
    ('plugin.lifecycle.manage', '管理插件生命周期', 'action', 'plugin', '允许启用、停用和卸载插件。', 1, 1, 30),
    ('plugin.settings.manage', '管理插件设置', 'action', 'plugin', '允许修改插件配置。', 1, 1, 40),
    ('plugin.permission.manage', '审批插件能力', 'action', 'plugin', '允许批准或撤销插件系统能力。', 1, 1, 50)
ON CONFLICT (permission_key) DO NOTHING;
INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE' FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'plugin' WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;
INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'plugin' WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
