/* Aquafish PostgreSQL V15：AI 提供商、模型、提示词、任务和审计。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_key VARCHAR(120) NOT NULL,
    name VARCHAR(191) NOT NULL,
    provider_type VARCHAR(64) NOT NULL,
    base_url VARCHAR(1000) NOT NULL,
    enabled SMALLINT NOT NULL DEFAULT 1,
    timeout_seconds INTEGER NOT NULL DEFAULT 60,
    extra_config_json TEXT,
    health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    last_checked_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_providers_provider_key UNIQUE (provider_key)
);
CREATE INDEX IF NOT EXISTS idx_ai_providers_enabled ON ${tablePrefix}ai_providers (enabled, provider_key);
COMMENT ON TABLE ${tablePrefix}ai_providers IS 'AI 服务提供商与非敏感连接配置表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_provider_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    credential_name VARCHAR(120) NOT NULL DEFAULT 'default',
    ciphertext TEXT NOT NULL,
    key_version VARCHAR(64) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    enabled SMALLINT NOT NULL DEFAULT 1,
    expires_at TIMESTAMP(3),
    last_used_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_provider_credentials_name UNIQUE (provider_id, credential_name)
);
CREATE INDEX IF NOT EXISTS idx_ai_provider_credentials_enabled
    ON ${tablePrefix}ai_provider_credentials (provider_id, enabled, expires_at);
COMMENT ON TABLE ${tablePrefix}ai_provider_credentials IS 'AI 提供商应用层加密凭据表，禁止保存明文密钥';

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    model_key VARCHAR(191) NOT NULL,
    name VARCHAR(191) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    context_window INTEGER,
    input_unit_price DECIMAL(18,8),
    output_unit_price DECIMAL(18,8),
    currency VARCHAR(16) NOT NULL DEFAULT 'USD',
    default_flag SMALLINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    capabilities_json TEXT,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_models_provider_model UNIQUE (provider_id, model_key)
);
CREATE INDEX IF NOT EXISTS idx_ai_models_type_enabled
    ON ${tablePrefix}ai_models (model_type, enabled, default_flag);
COMMENT ON TABLE ${tablePrefix}ai_models IS 'AI 提供商可用模型和能力清单表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_key VARCHAR(191) NOT NULL,
    name VARCHAR(191) NOT NULL,
    module_key VARCHAR(64) NOT NULL,
    system_prompt TEXT NOT NULL,
    user_prompt_template TEXT,
    variables_json TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_prompts_prompt_key_version UNIQUE (prompt_key, version)
);
CREATE INDEX IF NOT EXISTS idx_ai_prompts_module_status
    ON ${tablePrefix}ai_prompts (module_key, status);
COMMENT ON TABLE ${tablePrefix}ai_prompts IS '按业务模块版本化管理的 AI 提示词表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    module_key VARCHAR(64) NOT NULL,
    request_user_id BIGINT,
    provider_id BIGINT NOT NULL,
    model_id BIGINT NOT NULL,
    prompt_id BIGINT,
    target_type VARCHAR(64),
    target_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    input_hash VARCHAR(64) NOT NULL,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_cost DECIMAL(18,8) NOT NULL DEFAULT 0,
    result_reference VARCHAR(1000),
    error_code VARCHAR(120),
    error_summary VARCHAR(1000),
    started_at TIMESTAMP(3),
    finished_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_tasks_public_id UNIQUE (public_id)
);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_queue ON ${tablePrefix}ai_tasks (status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_user ON ${tablePrefix}ai_tasks (request_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_target ON ${tablePrefix}ai_tasks (target_type, target_id);
COMMENT ON TABLE ${tablePrefix}ai_tasks IS 'AI 异步任务、用量、成本和结果引用表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}ai_audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT,
    event_type VARCHAR(64) NOT NULL,
    operator_user_id BIGINT,
    provider_id BIGINT,
    model_id BIGINT,
    policy_result VARCHAR(64),
    detail_summary VARCHAR(1000),
    occurred_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_records_task
    ON ${tablePrefix}ai_audit_records (task_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ai_audit_records_event
    ON ${tablePrefix}ai_audit_records (event_type, occurred_at);
COMMENT ON TABLE ${tablePrefix}ai_audit_records IS '不保存敏感原文和密钥的 AI 安全审计事件表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('ai.view', '查看 AI 模块', 'menu', 'ai', '允许进入 AI 管理模块。', 1, 1, 10),
    ('ai.provider.manage', '管理 AI 提供商', 'action', 'ai', '允许维护提供商连接与加密凭据。', 1, 1, 20),
    ('ai.model.manage', '管理 AI 模型', 'action', 'ai', '允许维护模型能力和默认模型。', 1, 1, 30),
    ('ai.prompt.manage', '管理 AI 提示词', 'action', 'ai', '允许维护版本化提示词。', 1, 1, 40),
    ('ai.task.view', '查看 AI 任务', 'action', 'ai', '允许查看任务状态、用量和脱敏错误。', 1, 1, 50),
    ('ai.audit.view', '查看 AI 审计', 'action', 'ai', '允许查看 AI 安全审计事件。', 1, 1, 60)
ON CONFLICT (permission_key) DO NOTHING;
INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE' FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'ai' WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;
INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'ai' WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
