package com.aquafish.user.database.migration;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

class FlywayPostgresqlUserMigrationTest {

    @Test
    void shouldProvidePostgresqlV2UserSchema() throws IOException {
        String sql = readMigration(
            "db/migration/user/postgresql/V2__user_profile_statistics_points.sql"
        );

        assertTrue(sql.contains("${tablePrefix}user_profiles"));
        assertTrue(sql.contains("${tablePrefix}user_statistics"));
        assertTrue(sql.contains("ON CONFLICT (user_id) DO NOTHING"));
        assertPostgresqlOnly(sql);
    }

    @Test
    void shouldProvidePostgresqlV3CommunitySafetySchema() throws IOException {
        String sql = readMigration(
            "db/migration/user/postgresql/V3__user_tags_groups_bans.sql"
        );

        assertTrue(sql.contains("${tablePrefix}user_tags"));
        assertTrue(sql.contains("${tablePrefix}user_group_permissions"));
        assertTrue(sql.contains("${tablePrefix}ip_bans"));
        assertPostgresqlOnly(sql);
    }

    private void assertPostgresqlOnly(String sql) {
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertFalse(sql.contains("AUTO_INCREMENT"));
        assertFalse(sql.contains("ENGINE = InnoDB"));
        assertFalse(sql.contains("`"));
    }

    private String readMigration(String path) throws IOException {
        try (InputStream stream = getClass().getClassLoader().getResourceAsStream(path)) {
            assertNotNull(stream, "PostgreSQL 用户域迁移脚本必须打包进 user 模块");
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
