/* Aquafish PostgreSQL V16：统一搜索文档与可靠索引队列。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}search_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(64) NOT NULL,
    document_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    summary TEXT,
    search_text TEXT NOT NULL,
    url_path VARCHAR(1000) NOT NULL,
    owner_user_id BIGINT,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    source_updated_at TIMESTAMP(3) NOT NULL,
    indexed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_search_documents_type_id UNIQUE (document_type, document_id)
);
CREATE INDEX IF NOT EXISTS idx_search_documents_type_status
    ON ${tablePrefix}search_documents (document_type, status, source_updated_at);
CREATE INDEX IF NOT EXISTS idx_search_documents_owner
    ON ${tablePrefix}search_documents (owner_user_id, status);
COMMENT ON TABLE ${tablePrefix}search_documents IS '跨内容、论坛和用户模块的统一搜索投影表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}search_index_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(120) NOT NULL,
    document_type VARCHAR(64) NOT NULL,
    document_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP(3),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_search_index_queue_event_key UNIQUE (event_key)
);
CREATE INDEX IF NOT EXISTS idx_search_index_queue_delivery
    ON ${tablePrefix}search_index_queue (status, available_at, id);
CREATE INDEX IF NOT EXISTS idx_search_index_queue_document
    ON ${tablePrefix}search_index_queue (document_type, document_id);
COMMENT ON TABLE ${tablePrefix}search_index_queue IS '搜索索引增量更新和失败重试队列表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('search.view', '使用站内搜索', 'action', 'search', '允许搜索有权查看的站内内容。', 1, 1, 10),
    ('search.index.view', '查看搜索索引', 'menu', 'search', '允许查看索引状态和队列。', 1, 1, 20),
    ('search.index.manage', '管理搜索索引', 'action', 'search', '允许重试、重建和清理搜索索引。', 1, 1, 30)
ON CONFLICT (permission_key) DO NOTHING;
INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE' FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'search' WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;
INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'search' WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
