/* Aquafish PostgreSQL V9：内容、博客、页面和评论数据底座。 */

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    author_user_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    slug VARCHAR(191) NOT NULL,
    excerpt TEXT,
    content_text TEXT NOT NULL,
    cover_media_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    comment_status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    seo_title VARCHAR(240),
    seo_description VARCHAR(500),
    view_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    revision_number INTEGER NOT NULL DEFAULT 1,
    published_at TIMESTAMP(3),
    scheduled_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3),
    CONSTRAINT uk_content_articles_public_id UNIQUE (public_id),
    CONSTRAINT uk_content_articles_slug UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS idx_content_articles_status_publish
    ON ${tablePrefix}content_articles (status, published_at, id);
CREATE INDEX IF NOT EXISTS idx_content_articles_author
    ON ${tablePrefix}content_articles (author_user_id, created_at);
COMMENT ON TABLE ${tablePrefix}content_articles IS '博客文章、新闻和知识内容主表';
COMMENT ON COLUMN ${tablePrefix}content_articles.slug IS '站内唯一固定链接标识';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    parent_id BIGINT,
    author_user_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    slug VARCHAR(191) NOT NULL,
    content_text TEXT NOT NULL,
    template_key VARCHAR(120) NOT NULL DEFAULT 'default',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    sort_order INTEGER NOT NULL DEFAULT 0,
    seo_title VARCHAR(240),
    seo_description VARCHAR(500),
    revision_number INTEGER NOT NULL DEFAULT 1,
    published_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3),
    CONSTRAINT uk_content_pages_public_id UNIQUE (public_id),
    CONSTRAINT uk_content_pages_slug UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS idx_content_pages_parent_sort
    ON ${tablePrefix}content_pages (parent_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_content_pages_status
    ON ${tablePrefix}content_pages (status, published_at);
COMMENT ON TABLE ${tablePrefix}content_pages IS '关于页、协议页和自定义独立页面主表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    category_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(191) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    article_count BIGINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_categories_key UNIQUE (category_key),
    CONSTRAINT uk_content_categories_slug UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS idx_content_categories_parent_sort
    ON ${tablePrefix}content_categories (parent_id, sort_order, id);
COMMENT ON TABLE ${tablePrefix}content_categories IS '文章层级分类表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(191) NOT NULL,
    description TEXT,
    article_count BIGINT NOT NULL DEFAULT 0,
    enabled SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_tags_key UNIQUE (tag_key),
    CONSTRAINT uk_content_tags_slug UNIQUE (slug)
);
COMMENT ON TABLE ${tablePrefix}content_tags IS '文章扁平标签表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_article_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    is_primary SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_article_categories_pair UNIQUE (article_id, category_id)
);
CREATE INDEX IF NOT EXISTS idx_content_article_categories_category
    ON ${tablePrefix}content_article_categories (category_id, article_id);
COMMENT ON TABLE ${tablePrefix}content_article_categories IS '文章与分类多对多关系表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_article_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_article_tags_pair UNIQUE (article_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_content_article_tags_tag
    ON ${tablePrefix}content_article_tags (tag_id, article_id);
COMMENT ON TABLE ${tablePrefix}content_article_tags IS '文章与标签多对多关系表';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    parent_id BIGINT,
    root_id BIGINT,
    author_user_id BIGINT,
    guest_name VARCHAR(120),
    guest_email_hash VARCHAR(64),
    content_text TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    ip_hash VARCHAR(64),
    user_agent VARCHAR(500),
    reviewer_user_id BIGINT,
    reviewed_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_content_comments_target
    ON ${tablePrefix}content_comments (target_type, target_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_content_comments_parent
    ON ${tablePrefix}content_comments (parent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_content_comments_review
    ON ${tablePrefix}content_comments (status, created_at);
COMMENT ON TABLE ${tablePrefix}content_comments IS '文章和独立页面评论及审核表';
COMMENT ON COLUMN ${tablePrefix}content_comments.guest_email_hash IS '游客邮箱摘要，禁止保存明文邮箱';

CREATE TABLE IF NOT EXISTS ${tablePrefix}content_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    editor_user_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    content_text TEXT NOT NULL,
    change_summary VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_revisions_target_number
        UNIQUE (target_type, target_id, revision_number)
);
CREATE INDEX IF NOT EXISTS idx_content_revisions_editor
    ON ${tablePrefix}content_revisions (editor_user_id, created_at);
COMMENT ON TABLE ${tablePrefix}content_revisions IS '文章和页面不可覆盖的版本历史表';

INSERT INTO ${tablePrefix}permissions
    (permission_key, name, permission_type, module_key, description, built_in, enabled, sort_order)
VALUES
    ('content.view', '查看内容', 'menu', 'content', '允许进入内容管理模块。', 1, 1, 10),
    ('content.article.manage', '管理文章', 'action', 'content', '允许创建、编辑和归档文章。', 1, 1, 20),
    ('content.article.publish', '发布文章', 'action', 'content', '允许审核、发布和撤回文章。', 1, 1, 30),
    ('content.page.manage', '管理独立页面', 'action', 'content', '允许维护独立页面。', 1, 1, 40),
    ('content.taxonomy.manage', '管理分类标签', 'action', 'content', '允许维护文章分类和标签。', 1, 1, 50),
    ('content.comment.manage', '管理内容评论', 'action', 'content', '允许审核、标记垃圾和删除评论。', 1, 1, 60)
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO ${tablePrefix}role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM ${tablePrefix}roles r
JOIN ${tablePrefix}permissions p ON p.module_key = 'content'
WHERE r.role_key = 'super_admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO ${tablePrefix}admin_group_permissions (group_id, permission_id)
SELECT g.id, p.id
FROM ${tablePrefix}admin_groups g
JOIN ${tablePrefix}permissions p ON p.module_key = 'content'
WHERE g.group_key = 'super_admin'
ON CONFLICT (group_id, permission_id) DO NOTHING;
